version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      # Add your production environment variables here
      # - DATABASE_URL=postgresql://user:password@postgres:5432/football_transfers
      # - SECRET_KEY=your-secret-key-here
      # - ALLOWED_ORIGINS=https://yourdomain.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment if you want to add a database
    # depends_on:
    #   - postgres

  # Uncomment for database support
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: football_transfers
  #     POSTGRES_USER: fastapi
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U fastapi"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # Uncomment for Redis (for caching/sessions)
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

# volumes:
#   postgres_data: 