apiVersion: v1
kind: Service
metadata:
  name: feed-ingestion-service
  namespace: briefings-feed
  labels:
    app: feed-ingestion
spec:
  selector:
    app: feed-ingestion
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP 