apiVersion: v1
kind: Service
metadata:
  name: my-briefings-service
  namespace: my-briefings
  labels:
    app: my-briefings-app
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  selector:
    app: my-briefings-app 